# Generated by Django 5.2.7 on 2025-11-13 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_lat', models.FloatField(default=0.0)),
                ('order_long', models.FloatField(default=0.0)),
                ('order_address', models.CharField(default='Lấy tại nhà hàng')),
                ('order_phone', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('cooking', 'Đang chuẩn bị'), ('delivering', 'Đang giao'), ('finish', 'Hoàn tất')], default='pending', max_length=20)),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_userShipper', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_userStaff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_voucher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItem_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem_food', to='foods.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderItem', to='ordering.order')),
            ],
        ),
    ]
