# Generated by Django 5.2.7 on 2025-11-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_order_voucher'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_voucher', to='voucher.voucher'),
        ),
    ]
