# Generated by Django 5.2.7 on 2025-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_alter_order_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('cooking', 'Đang chuẩn bị'), ('delivering', 'Đang giao'), ('finish', 'Hoàn tất'), ('canceled', 'Hủy đơn')], default='pending', max_length=20),
        ),
    ]
