# Generated by Django 5.2.7 on 2025-11-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('canceled', 'Hủy thanh toán')], default='pending', max_length=25),
        ),
    ]
