# Generated by Django 5.2.7 on 2025-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_name',
            field=models.CharField(default='Tri ân cuối năm', max_length=255),
            preserve_default=False,
        ),
    ]
