# Generated by Django 5.2.7 on 2025-11-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
