# Generated by Django 5.2.7 on 2025-11-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_name', models.CharField(max_length=100)),
                ('catalog_img', models.ImageField(blank=True, null=True, upload_to='catalogs/')),
            ],
        ),
    ]
